language: generic
sudo: required
services:
  - docker


before-install:
  - docker build -t hirschstevenw/dokcer-react -f Dockerfile.dev .



script:
  - docker run -e CI=true hirschstevenw/docker-react npm run test -- --coverage

